### ISSUE TITLE
Anvil consumes entire stack in "sacrifice" slot when not repairing

### ISSUE THREAD

**Issue by James103** [Devan-Kerman/Stacc#5]
Minecraft 1.16.1
Stacc 1.16.1 4

When an anvil is used (besides for repairing purposes), the entire stack inside the 'sacrifice' slot is consumed, regardless of what's in the 'target' slot. For example, combining a single Diamond Helmet with a Protection IV book (stacked to 1,000,000) will consume all 1,000,000 Protection IV books to produce a single Protection IV diamond helmet at a cost of 4 XP levels, where it should have consumed as many Protection IV books as there were Diamond Helmets in the "target" slot. If there are not enough items in the "target" slot (in this case Protection IV books), then the remainder of the items in the "sacrifice" slot are left unenchanted.

Additionally, it is "too expensive" (40 XP levels or more) to combine more than 1 item in the "target" slot at once (stacked) with something in the "sacrifice" slot, whether it be an elytra with Unbreaking and Mending, or a Diamond Helmet with itself where both are enchanted differently.

**Comment by Ueaj-Kerman** [comment]
fixed in katest release, 1 billion swords now require 1 billion books to craft

**Comment by James103** [comment]
The XP cost requirement is still not fixed, IMO. It still returns a cost of 40 XP levels or more to combine more than 1 item in the "target" slot with an equal or greater number of the item in the "sacrifice" slot. Is that intended?

**Comment by Ueaj-Kerman** [comment]
Not intended, will fix

**Comment by Ueaj-Kerman** [comment]
fixed, will be in next release
